; This file was auto-generated by drush make

core = 7.x
api = 2

; Projects
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"
projects[ctools][patch][0] = "http://drupal.org/files/ctools-n1925018-12.patch"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0-beta2"

projects[media][subdir] = contrib
projects[media][version] = "2.0-unstable7"

projects[file_entity][subdir] = contrib
projects[file_entity][version] = "2.0-unstable7"

projects[features_extra][subdir] = "contrib"
projects[features_extra][version] = "1.0-beta1"
